/**
 * Mock Data for Demo/Offline Mode
 * Professional sample data showcasing app features
 */

export const mockProducts = [
  {
    id: 'prod_1',
    slug: 'amul-milk-full-cream',
    title: 'Amul Full Cream Milk - 1L',
    brand: { name: 'Amul' },
    category: { name: 'Dairy & Eggs', slug: 'dairy-eggs' },
    heroImage: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&h=800&fit=crop',
    shortSummary: '100% pure milk with no added preservatives. Rich source of calcium, protein and vitamins.',
    description: 'Fresh full cream milk from Amul. Rich in calcium and protein. Perfect for daily nutrition.',
    healthScore: 85,
    isPalmOilFree: true,
    isLowSugar: true,
    isArtificialColorFree: true,
    isWholeGrain: false,
    isMeetsStandard: true,
    ingredientsText: 'Fresh cow milk, Vitamin D3',
    allergensText: 'Contains: Milk',
    nutritionJson: {
      calories: 150,
      protein: '8g',
      totalFat: '8g',
      calcium: '30% DV',
    },
    affiliateLinks: [
      {
        id: 'aff_1',
        merchant: 'AMAZON',
        url: 'https://amazon.in',
        isActive: true,
      },
      {
        id: 'aff_2',
        merchant: 'FLIPKART',
        url: 'https://flipkart.com',
        isActive: true,
      },
    ],
  },
  {
    id: 'prod_2',
    slug: 'organic-india-tulsi-tea',
    title: 'Organic India Tulsi Green Tea - 25 Bags',
    brand: { name: 'Organic India' },
    category: { name: 'Beverages', slug: 'beverages' },
    heroImage: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&h=800&fit=crop',
    shortSummary: 'Certified organic tea with holy basil. Rich in antioxidants. Caffeine-free wellness drink.',
    description: 'Premium organic Tulsi green tea. Boosts immunity and reduces stress naturally.',
    healthScore: 92,
    isPalmOilFree: true,
    isLowSugar: true,
    isArtificialColorFree: true,
    isWholeGrain: false,
    isMeetsStandard: true,
    ingredientsText: 'Organic Tulsi leaves (Holy Basil), Organic Green Tea',
    allergensText: 'None',
    nutritionJson: {
      calories: 0,
      caffeine: '0mg',
      antioxidants: 'High',
    },
    affiliateLinks: [
      {
        id: 'aff_3',
        merchant: 'AMAZON',
        url: 'https://amazon.in',
        isActive: true,
      },
    ],
  },
  {
    id: 'prod_3',
    slug: 'patanjali-chana-sattu',
    title: 'Patanjali Chana Sattu - 500g',
    brand: { name: 'Patanjali' },
    category: { name: 'Health Foods', slug: 'health-foods' },
    heroImage: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&h=800&fit=crop',
    shortSummary: 'Natural protein powder made from roasted Bengal gram. No additives. Ancient superfood.',
    description: 'Traditional roasted gram flour. High in protein and fiber. Perfect for healthy drinks and snacks.',
    healthScore: 88,
    isPalmOilFree: true,
    isLowSugar: true,
    isArtificialColorFree: true,
    isWholeGrain: true,
    isMeetsStandard: true,
    ingredientsText: 'Roasted Bengal Gram (Chana)',
    allergensText: 'May contain: Traces of gluten',
    nutritionJson: {
      calories: 380,
      protein: '20g',
      fiber: '10g',
      iron: '15% DV',
    },
    affiliateLinks: [
      {
        id: 'aff_4',
        merchant: 'AMAZON',
        url: 'https://amazon.in',
        isActive: true,
      },
      {
        id: 'aff_5',
        merchant: 'FLIPKART',
        url: 'https://flipkart.com',
        isActive: true,
      },
    ],
  },
  {
    id: 'prod_4',
    slug: 'mother-dairy-curd',
    title: 'Mother Dairy Fresh Curd - 400g',
    brand: { name: 'Mother Dairy' },
    category: { name: 'Dairy & Eggs', slug: 'dairy-eggs' },
    heroImage: 'https://images.unsplash.com/photo-1571212515416-fca296703ecf?w=800&h=800&fit=crop',
    shortSummary: 'Live culture curd with active probiotics. Aids digestion. Made from pure milk.',
    description: 'Fresh creamy curd made from pure milk. Rich in probiotics for gut health.',
    healthScore: 82,
    isPalmOilFree: true,
    isLowSugar: true,
    isArtificialColorFree: true,
    isWholeGrain: false,
    isMeetsStandard: true,
    ingredientsText: 'Toned Milk, Bacterial Culture',
    allergensText: 'Contains: Milk',
    nutritionJson: {
      calories: 100,
      protein: '6g',
      probiotics: 'Live cultures',
      calcium: '20% DV',
    },
    affiliateLinks: [
      {
        id: 'aff_6',
        merchant: 'AMAZON',
        url: 'https://amazon.in',
        isActive: true,
      },
    ],
  },
  {
    id: 'prod_5',
    slug: 'organic-honey-raw',
    title: 'Pure Raw Organic Honey - 500g',
    brand: { name: 'Organic India' },
    category: { name: 'Sweeteners', slug: 'sweeteners' },
    heroImage: 'https://images.unsplash.com/photo-1587049352846-4a222e784210?w=800&h=800&fit=crop',
    shortSummary: 'Unprocessed raw honey with natural enzymes. Rich in antioxidants. Perfect natural sweetener.',
    description: 'Pure, raw, unfiltered honey straight from beehives. Contains natural pollen and propolis.',
    healthScore: 78,
    isPalmOilFree: true,
    isLowSugar: false,
    isArtificialColorFree: true,
    isWholeGrain: false,
    isMeetsStandard: true,
    ingredientsText: 'Raw Honey (100%)',
    allergensText: 'None',
    nutritionJson: {
      calories: 320,
      sugar: '80g',
      antioxidants: 'High',
    },
    affiliateLinks: [
      {
        id: 'aff_7',
        merchant: 'AMAZON',
        url: 'https://amazon.in',
        isActive: true,
      },
    ],
  },
  {
    id: 'prod_6',
    slug: 'millet-cookies',
    title: 'Ragi & Jowar Millet Cookies - 200g',
    brand: { name: 'Healthy Bites' },
    category: { name: 'Snacks', slug: 'snacks' },
    heroImage: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&h=800&fit=crop',
    shortSummary: 'Wholesome cookies made with finger millet and sorghum. No maida. Low sugar.',
    description: 'Delicious cookies made with nutritious millets. Perfect guilt-free snacking.',
    healthScore: 86,
    isPalmOilFree: true,
    isLowSugar: true,
    isArtificialColorFree: true,
    isWholeGrain: true,
    isMeetsStandard: true,
    ingredientsText: 'Ragi flour, Jowar flour, Jaggery, Coconut oil, Baking soda',
    allergensText: 'May contain traces of nuts',
    nutritionJson: {
      calories: 450,
      protein: '8g',
      fiber: '12g',
      iron: '20% DV',
    },
    affiliateLinks: [
      {
        id: 'aff_8',
        merchant: 'AMAZON',
        url: 'https://amazon.in',
        isActive: true,
      },
      {
        id: 'aff_9',
        merchant: 'FLIPKART',
        url: 'https://flipkart.com',
        isActive: true,
      },
    ],
  },
];

export const mockCategories = [
  {
    id: 'cat_1',
    name: 'Dairy & Eggs',
    slug: 'dairy-eggs',
  },
  {
    id: 'cat_2',
    name: 'Beverages',
    slug: 'beverages',
  },
  {
    id: 'cat_3',
    name: 'Health Foods',
    slug: 'health-foods',
  },
  {
    id: 'cat_4',
    name: 'Sweeteners',
    slug: 'sweeteners',
  },
  {
    id: 'cat_5',
    name: 'Snacks',
    slug: 'snacks',
  },
];

export const mockArticles = [
  {
    id: 'art_1',
    slug: 'understanding-health-scores',
    title: 'Understanding Health Scores: What They Mean for You',
    excerpt: 'Learn how we calculate health scores and what makes a product truly healthy. Our comprehensive guide breaks down the science.',
    category: 'Education',
    publishedAt: new Date('2024-01-15'),
    coverImage: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800',
  },
  {
    id: 'art_2',
    slug: 'reading-food-labels',
    title: 'The Ultimate Guide to Reading Food Labels',
    excerpt: 'Master the art of decoding nutrition labels and ingredient lists. Know exactly what you are putting in your body.',
    category: 'Guide',
    publishedAt: new Date('2024-01-10'),
    coverImage: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
  },
  {
    id: 'art_3',
    slug: 'palm-oil-hidden-dangers',
    title: 'Palm Oil: The Hidden Ingredient You Should Avoid',
    excerpt: 'Discover why palm oil is harmful to your health and the environment. Learn to identify it in products.',
    category: 'Ingredients',
    publishedAt: new Date('2024-01-05'),
    coverImage: 'https://images.unsplash.com/photo-1608797178974-15b35a64ede9?w=800',
  },
];
